In [1]:
import pandas as pd

In [2]:
trans = pd.read_csv('C:\\Users\dmitr\Desktop\LEADROCK\\trans_05-12.21.tsv', sep='\t')
trans

         user_id amount  balance           created_at         payment_type
0          14035  16,00  1158,00  2021-12-31 23:59:46  Транзакция по лидам
1           9111  14,00   209,00  2021-12-31 23:59:41  Транзакция по лидам
2           9111   0,00   195,00  2021-12-31 23:59:27  Транзакция по лидам
3          15501   0,00   388,00  2021-12-31 23:58:56  Транзакция по лидам
4          14217   0,00  2062,00  2021-12-31 23:58:44  Транзакция по лидам
...          ...    ...      ...                  ...                  ...
4897824    13483   0,00   420,00  2021-05-01 00:01:23  Транзакция по лидам
4897825    13483   0,00   420,00  2021-05-01 00:01:20  Транзакция по лидам
4897826     9069   0,00  2412,00  2021-05-01 00:01:02  Транзакция по лидам
4897827     2536   0,00   372,00  2021-05-01 00:00:56  Транзакция по лидам
4897828     7463   0,00  5136,00  2021-05-01 00:00:02  Транзакция по лидам

[4897829 rows x 5 columns]

In [3]:
trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4897829 entries, 0 to 4897828
Data columns (total 5 columns):
 #   Column        Dtype
---  ------        -----
 0   user_id       int64
 1   amount        object
 2   balance       object
 3   created_at    object
 4   payment_type  object
dtypes: int64(1), object(4)
memory usage: 186.8+ MB

In [4]:
sp_3 = pd.read_excel('C:\\Users\dmitr\Desktop\LEADROCK\Список-3.xlsx', sheet_name='TDSheet')
sp_3

,Дата,Номер,Период инвойса,Расчетный счет,Валюта отгрузки,Сумма отгрузки,Сумма оплаты,Сумма комиссии,Статья затрат,Статья затрат на комиссию,Комментарий,Контрагент,Проект,Внутрифирменные расчеты,Вид операции,Ответственный,Уникальный идентификатор загрузки
0,01.10.2021 15:23:00,90156.0,NaN,Capitalist SADE (RUR),NaN,NaN,3691,203.01,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,Payout for webmaster from request 44902 in pac...,NaN,Leadrock,NaN,Расчеты с поставщиками,Трофимова Кристина,ebeb044c-444e-4413-8140-31fa183b0d03
1,01.10.2021 15:23:00,90157.0,NaN,Capitalist SADE (RUR),NaN,NaN,14499,797.45,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,Payout for webmaster from request 44902 in pac...,NaN,Leadrock,NaN,Расчеты с поставщиками,Трофимова Кристина,ebeb044c-444e-4413-8140-31fa183b0d03
2,01.10.2021 15:23:00,90158.0,NaN,Capitalist SADE (RUR),NaN,NaN,3691,203.01,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,Payout for webmaster from request 44903 in pac...,NaN,Leadrock,NaN,Расчеты с поставщиками,Трофимова Кристина,ebeb044c-444e-4413-8140-31fa183b0d03
3,01.10.2021 15:23:00,90159.0,NaN,Capitalist SADE (RUR),NaN,NaN,14499,797.45,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,Payout for webmaster from request 44903 in pac...,NaN,Leadrock,NaN,Расчеты с поставщиками,Трофимова Кристина,ebeb044c-444e-4413-8140-31fa183b0d03
4,01.10.2021 15:23:00,90160.0,NaN,Capitalist SADE (RUR),NaN,NaN,2182.8,120.06,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,Payout for webmaster from request 44950 in pac...,NaN,Leadrock,NaN,Расчеты с поставщиками,Трофимова Кристина,ebeb044c-444e-4413-8140-31fa183b0d03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1211,08.10.2021 0:00:00,95054.0,NaN,Григорьев ИП,NaN,NaN,77771.86,NaN,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,NaN,Калина И.А.,NaN,NaN,Расчеты с поставщиками,Трофимова Кристина,75cc815b-a87b-452d-8039-ee6b623b6e27
1212,13.10.2021 0:00:00,95055.0,NaN,Григорьев ИП,NaN,NaN,844226.81,NaN,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,NaN,Путков А.В.,NaN,NaN,Расчеты с поставщиками,Трофимова Кристина,75cc815b-a87b-452d-8039-ee6b623b6e27
1213,17.10.2021 0:00:00,95057.0,NaN,Григорьев ИП,NaN,NaN,94250.62,NaN,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,NaN,Калина И.А.,NaN,NaN,Расчеты с поставщиками,Трофимова Кристина,75cc815b-a87b-452d-8039-ee6b623b6e27
1214,17.10.2021 0:00:00,95058.0,NaN,Григорьев ИП,NaN,NaN,111332.63,NaN,Выплаты вебмастерам (Лидрок),Комиссии при выплате вебам,NaN,Калина Е.М.,NaN,NaN,Расчеты с поставщиками,Трофимова Кристина,75cc815b-a87b-452d-8039-ee6b623b6e27
1215,NaN,NaN,NaN,NaN,NaN,"11 209 097,04","120 963 234,80","535 916,79",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
sp_3['Расчетный счет'].value_counts()

Capitalist SADE (USD)    711
Capitalist SADE (RUR)    380
WebMoney Рост (USD)       95
Payoneer (USD)            12
Логос ООО                  9
Григорьев ИП               6
Касса (RUR)                2
Name: Расчетный счет, dtype: int64

In [39]:
sp_3['Комментарий'].unique()

array(['Payout for webmaster from request 44902 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44903 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44950 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44883 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44885 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44890 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44906 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44907 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44927 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44934 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44936 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44892 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44912 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44918 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44919 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44930 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44937 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 45037 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45029 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45028 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45026 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45024 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45022 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45016 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45006 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45005 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45004 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45003 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45001 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 44989 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 44988 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 44986 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 44969 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 44966 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 44962 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 44961 in package 6121 at 2021-10-04 12:00',
       'Payout for webmaster from request 45056 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45043 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45042 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45127 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45118 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45117 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45116 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45115 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45107 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45105 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45084 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45076 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45072 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45057 in package 6123 at 2021-10-06 14:00',
       'Payout for webmaster from request 45200 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45196 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45195 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45193 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45192 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45190 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45189 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45185 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45183 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45178 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45175 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45173 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45172 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45165 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45151 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45141 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45139 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45133 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45132 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45130 in package 6126 at 2021-10-08 12:00',
       'Payout for webmaster from request 45283 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45282 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45280 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45279 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45278 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45277 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45275 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45269 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45268 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45254 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45252 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45250 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45244 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45236 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45214 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45295 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45294 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45292 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45288 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45287 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45286 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45285 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45284 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45234 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45255 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45276 in package 6130 at 2021-10-11 13:00',
       'Payout for webmaster from request 45359 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45358 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45355 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45350 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45335 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45320 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45313 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45312 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45309 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45308 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45347 in package 6134 at 2021-10-13 13:00',
       'Payout for webmaster from request 45325 in package 6134 at 2021-10-13 13:00',
       'Payout for webmaster from request 45314 in package 6134 at 2021-10-13 13:00',
       'ayout for webmaster from request 45312 in package 6133 at 2021-10-13 13:00',
       'Payout for webmaster from request 45456 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45453 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45452 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45444 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45434 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45431 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45430 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45419 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45408 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45376 in package 6140 at 2021-10-15 12:00',
       'Payout for webmaster from request 45546 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45545 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45544 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45543 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45542 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45541 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45527 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45525 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45523 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45514 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45508 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45504 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45482 in package 6144 at 2021-10-19 08:00',
       'Payout for webmaster from request 45583 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45553 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45560 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45594 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45595 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45598 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45606 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45610 in package 6149 at 2021-10-20 13:00',
       'Payout for webmaster from request 45637 in package 6151 at 2021-10-21 14:00',
       'Payout for webmaster from request 45719 in package 6154 at 2021-10-22 12:00',
       'Payout for webmaster from request 45685 in package 6154 at 2021-10-22 12:00',
       'Payout for webmaster from request 45659 in package 6154 at 2021-10-22 12:00',
       'Payout for webmaster from request 45809 in package 6159 at 2021-10-25 14:00',
       'Payout for webmaster from request 45803 in package 6159 at 2021-10-25 14:00',
       'Payout for webmaster from request 45802 in package 6159 at 2021-10-25 14:00',
       'Payout for webmaster from request 45758 in package 6159 at 2021-10-25 14:00',
       'Payout for webmaster from request 45757 in package 6159 at 2021-10-25 14:00',
       'Payout for webmaster from request 45752 in package 6159 at 2021-10-25 14:00',
       'Payout for webmaster from request 45740 in package 6159 at 2021-10-25 14:00',
       'Payout for webmaster from request 45833 in package 6161 at 2021-10-26 14:00',
       'Payout for webmaster from request 45898 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45897 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45884 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45883 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45877 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45876 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45870 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45869 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45868 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45866 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45842 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45835 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45834 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45830 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45829 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45828 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45827 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45826 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45825 in package 6164 at 2021-10-27 12:00',
       'Payout for webmaster from request 45954 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45948 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45938 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45934 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45933 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45925 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45923 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45920 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45919 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 45913 in package 6169 at 2021-10-29 12:00',
       'Payout for webmaster from request 44873 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44876 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44877 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44878 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44879 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44880 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44881 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44882 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44884 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44895 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44898 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44899 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44917 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44925 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44939 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44940 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44944 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44904 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44914 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44915 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44932 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44933 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44938 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44943 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44945 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44949 in package 6117 at 2021-10-01 12:00',
       'Payout for webmaster from request 44952 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44947 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44946 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44942 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44941 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44935 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44931 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44929 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44928 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44926 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44924 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44923 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44922 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44921 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44920 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44916 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44913 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44911 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44910 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44909 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44908 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44905 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44901 in package 6116 at 2021-10-01 12:00',
       'Payout for webmaster from request 44900 in package 6116 at 2021-10-01 12:00',

In [6]:
sp_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1216 entries, 0 to 1215
Data columns (total 17 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Дата                               1215 non-null   object
 1   Номер                              1215 non-null   float64
 2   Период инвойса                     0 non-null      float64
 3   Расчетный счет                     1215 non-null   object
 4   Валюта отгрузки                    0 non-null      float64
 5   Сумма отгрузки                     1 non-null      object
 6   Сумма оплаты                       1216 non-null   object
 7   Сумма комиссии                     891 non-null    object
 8   Статья затрат                      1215 non-null   object
 9   Статья затрат на комиссию          1215 non-null   object
 10  Комментарий                        1209 non-null   object
 11  Контрагент                         117 non-null    object
 12  Проект                             1209 non-null   object
 13  Внутрифирменные расчеты            0 non-null      float64
 14  Вид операции                       1215 non-null   object
 15  Ответственный                      1215 non-null   object
 16  Уникальный идентификатор загрузки  1215 non-null   object
dtypes: float64(4), object(13)
memory usage: 161.6+ KB

In [7]:
sp_3['Дата']= pd.to_datetime(sp_3['Дата'], format='%d.%m.%Y %H:%M:%S')

In [8]:
#oct_man = pd.read_csv('C:\\Users\dmitr\Desktop\LEADROCK\october_manual.tsv', sep='\t')
#oct_man

In [9]:
#res_by_mon = pd.read_csv('C:\\Users\dmitr\Desktop\LEADROCK\\result_by_month_payment_type.tsv', sep='|')
#res_by_mon

In [10]:
sp_3['com'] = sp_3['Комментарий'].str.extract('(from request \d+)')
sp_3['request'] = sp_3['com'].str.extract('(\d+)')
sp_3['request'] = pd.to_numeric(sp_3['request'])
display(sp_3.groupby('request')['Сумма оплаты'].sum().sum())
df = sp_3.pivot_table(index = 'request',values = 'Сумма оплаты', aggfunc = 'sum')
df

5235501.719999997

         Сумма оплаты
request
44872.0        150.00
44873.0        500.00
44874.0         52.00
44875.0        162.00
44876.0        315.00
...               ...
45967.0         90.00
45969.0         90.00
45972.0        700.00
45973.0        254.59
45976.0       1586.00

[888 rows x 1 columns]

In [38]:
df['Сумма оплаты'].sum()

5235501.720000001

In [11]:
payout_request = pd.read_csv('C:\\Users\dmitr\Desktop\LEADROCK\\payout_request.csv')
payout_request

         id   amount     rub  created_at          up  status  system_id
0     44872   150.00     0.0  1632915712  1632915712       2       3320
1     44873   500.00     0.0  1632917840  1632917840       2       4364
2     44874    52.00     0.0  1632922859  1632922859       2       3849
3     44875   162.00     0.0  1632928025  1632928025       2       2641
4     44876   315.00     0.0  1632946985  1632946985       2       4268
...     ...      ...     ...         ...         ...     ...        ...
1100  45972   700.00     0.0  1635505271  1635505271       2       4751
1101  45973   254.59     0.0  1635506686  1635506686       2       4149
1102  45974  2000.00     0.0  1635510430  1635510430       2       4840
1103  45975   135.00  9520.2  1635511675  1635511675       2       5456
1104  45976  1586.00     0.0  1635524118  1635524118       2       5109

[1105 rows x 7 columns]

In [12]:
payout_request['created_at'] = pd.to_datetime(payout_request['created_at'], unit='s')
payout_request['created_day'] = payout_request['created_at'].dt.floor('1D')
payout_request

,id,amount,rub,created_at,up,status,system_id,created_day
0,44872,150.00,0.0,2021-09-29 11:41:52,1632915712,2,3320,2021-09-29
1,44873,500.00,0.0,2021-09-29 12:17:20,1632917840,2,4364,2021-09-29
2,44874,52.00,0.0,2021-09-29 13:40:59,1632922859,2,3849,2021-09-29
3,44875,162.00,0.0,2021-09-29 15:07:05,1632928025,2,2641,2021-09-29
4,44876,315.00,0.0,2021-09-29 20:23:05,1632946985,2,4268,2021-09-29
...,...,...,...,...,...,...,...,...
1100,45972,700.00,0.0,2021-10-29 11:01:11,1635505271,2,4751,2021-10-29
1101,45973,254.59,0.0,2021-10-29 11:24:46,1635506686,2,4149,2021-10-29
1102,45974,2000.00,0.0,2021-10-29 12:27:10,1635510430,2,4840,2021-10-29
1103,45975,135.00,9520.2,2021-10-29 12:47:55,1635511675,2,5456,2021-10-29
1104,45976,1586.00,0.0,2021-10-29 16:15:18,1635524118,2,5109,2021-10-29

In [13]:
payout_request['created_at'].max()

Timestamp('2021-10-29 16:15:18')

In [14]:
currency = pd.read_excel('C:\\Users\dmitr\Desktop\LEADROCK\\курс.xlsx', sheet_name='RC')
currency

         data     curs
0  2021-10-30  70.5200
1  2021-10-29  70.5207
2  2021-10-28  69.8104
3  2021-10-27  69.5526
4  2021-10-26  70.1345
5  2021-10-25  70.8623
6  2021-10-24  70.8623
7  2021-10-23  70.8623
8  2021-10-22  70.9904
9  2021-10-21  71.0555
10 2021-10-20  70.9674
11 2021-10-19  71.1714
12 2021-10-18  71.2371
13 2021-10-17  71.2371
14 2021-10-16  71.2371
15 2021-10-15  71.7846
16 2021-10-14  71.8577
17 2021-10-13  71.8801
18 2021-10-12  71.6373
19 2021-10-11  71.9882
20 2021-10-10  71.9882
21 2021-10-09  71.9882
22 2021-10-08  72.2854
23 2021-10-07  72.5682
24 2021-10-06  72.5686
25 2021-10-05  72.9239
26 2021-10-04  72.9215
27 2021-10-03  72.9215
28 2021-10-02  72.9215
29 2021-10-01  72.6642
30 2021-09-30  72.7608
31 2021-09-29  72.5083

In [15]:
payout = payout_request.merge(currency, left_on='created_day', right_on='data' , how='left')

In [16]:
payout['sum'] = payout['amount']* payout['curs']
payout

,id,amount,rub,created_at,up,status,system_id,created_day,data,curs,sum
0,44872,150.00,0.0,2021-09-29 11:41:52,1632915712,2,3320,2021-09-29,2021-09-29,72.5083,10876.245000
1,44873,500.00,0.0,2021-09-29 12:17:20,1632917840,2,4364,2021-09-29,2021-09-29,72.5083,36254.150000
2,44874,52.00,0.0,2021-09-29 13:40:59,1632922859,2,3849,2021-09-29,2021-09-29,72.5083,3770.431600
3,44875,162.00,0.0,2021-09-29 15:07:05,1632928025,2,2641,2021-09-29,2021-09-29,72.5083,11746.344600
4,44876,315.00,0.0,2021-09-29 20:23:05,1632946985,2,4268,2021-09-29,2021-09-29,72.5083,22840.114500
...,...,...,...,...,...,...,...,...,...,...,...
1100,45972,700.00,0.0,2021-10-29 11:01:11,1635505271,2,4751,2021-10-29,2021-10-29,70.5207,49364.490000
1101,45973,254.59,0.0,2021-10-29 11:24:46,1635506686,2,4149,2021-10-29,2021-10-29,70.5207,17953.865013
1102,45974,2000.00,0.0,2021-10-29 12:27:10,1635510430,2,4840,2021-10-29,2021-10-29,70.5207,141041.400000
1103,45975,135.00,9520.2,2021-10-29 12:47:55,1635511675,2,5456,2021-10-29,2021-10-29,70.5207,9520.294500
1104,45976,1586.00,0.0,2021-10-29 16:15:18,1635524118,2,5109,2021-10-29,2021-10-29,70.5207,111845.830200

In [17]:
payout1 = payout.merge(df, left_on='id', right_on='request' , how='left')

In [18]:
payout2 = payout1[payout1['Сумма оплаты'].isna()]
payout2[payout2['status'] ==2]

,id,amount,rub,created_at,up,status,system_id,created_day,data,curs,sum,Сумма оплаты
15,44887,59.0,0.0,2021-09-30 07:18:50,1632986330,2,697,2021-09-30,2021-09-30,72.7608,4292.8872,NaN
79,44951,1036.0,0.0,2021-10-01 10:44:16,1633085056,2,3446,2021-10-01,2021-10-01,72.6642,75280.1112,NaN
81,44953,5000.0,0.0,2021-10-01 14:54:22,1633100062,2,5367,2021-10-01,2021-10-01,72.6642,363321.0000,NaN
87,44959,1400.0,0.0,2021-10-02 11:32:27,1633174347,2,3067,2021-10-02,2021-10-02,72.9215,102090.1000,NaN
96,44968,2000.0,0.0,2021-10-03 08:51:54,1633251114,2,4840,2021-10-03,2021-10-03,72.9215,145843.0000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1020,45892,1280.0,0.0,2021-10-27 10:04:21,1635329061,2,5153,2021-10-27,2021-10-27,69.5526,89027.3280,NaN
1063,45935,1661.0,0.0,2021-10-29 04:10:09,1635480609,2,4611,2021-10-29,2021-10-29,70.5207,117134.8827,NaN
1065,45937,2044.0,0.0,2021-10-29 06:03:05,1635487385,2,3219,2021-10-29,2021-10-29,70.5207,144144.3108,NaN
1102,45974,2000.0,0.0,2021-10-29 12:27:10,1635510430,2,4840,2021-10-29,2021-10-29,70.5207,141041.4000,NaN
1103,45975,135.0,9520.2,2021-10-29 12:47:55,1635511675,2,5456,2021-10-29,2021-10-29,70.5207,9520.2945,NaN

In [19]:
payout2[payout2['status'] ==2]['sum'].sum()

12911213.303288

In [20]:
payout1[payout1['Сумма оплаты'].isna()]['sum'].sum()

26143157.424628

In [21]:
total = payout.merge(df, left_on='id', right_on='request' , how='right')
total

,id,amount,rub,created_at,up,status,system_id,created_day,data,curs,sum,Сумма оплаты
0,44872,150.00,0.0,2021-09-29 11:41:52,1632915712,2,3320,2021-09-29,2021-09-29,72.5083,10876.245000,150.00
1,44873,500.00,0.0,2021-09-29 12:17:20,1632917840,2,4364,2021-09-29,2021-09-29,72.5083,36254.150000,500.00
2,44874,52.00,0.0,2021-09-29 13:40:59,1632922859,2,3849,2021-09-29,2021-09-29,72.5083,3770.431600,52.00
3,44875,162.00,0.0,2021-09-29 15:07:05,1632928025,2,2641,2021-09-29,2021-09-29,72.5083,11746.344600,162.00
4,44876,315.00,0.0,2021-09-29 20:23:05,1632946985,2,4268,2021-09-29,2021-09-29,72.5083,22840.114500,315.00
...,...,...,...,...,...,...,...,...,...,...,...,...
883,45967,90.00,0.0,2021-10-29 10:42:50,1635504170,2,5299,2021-10-29,2021-10-29,70.5207,6346.863000,90.00
884,45969,90.00,0.0,2021-10-29 10:57:00,1635505020,2,4925,2021-10-29,2021-10-29,70.5207,6346.863000,90.00
885,45972,700.00,0.0,2021-10-29 11:01:11,1635505271,2,4751,2021-10-29,2021-10-29,70.5207,49364.490000,700.00
886,45973,254.59,0.0,2021-10-29 11:24:46,1635506686,2,4149,2021-10-29,2021-10-29,70.5207,17953.865013,254.59
887,45976,1586.00,0.0,2021-10-29 16:15:18,1635524118,2,5109,2021-10-29,2021-10-29,70.5207,111845.830200,1586.00

In [22]:
total['status'].value_counts()

2    888
Name: status, dtype: int64

In [23]:
total1 = total[total['amount']!=total['Сумма оплаты']]
total1

,id,amount,rub,created_at,up,status,system_id,created_day,data,curs,sum,Сумма оплаты
11,44883,44.0,3190.44,2021-09-29 20:49:25,1632948565,2,4699,2021-09-29,2021-09-29,72.5083,3190.3652,3190.44
13,44885,150.0,10876.50,2021-09-30 01:16:20,1632964580,2,5159,2021-09-30,2021-09-30,72.7608,10914.1200,10876.50
17,44890,40.0,2900.40,2021-09-30 08:30:00,1632990600,2,5364,2021-09-30,2021-09-30,72.7608,2910.4320,2900.40
19,44892,123.0,8918.73,2021-09-30 09:16:13,1632993373,2,4066,2021-09-30,2021-09-30,72.7608,8949.5784,8918.73
29,44902,250.0,18190.00,2021-09-30 14:08:34,1633010914,2,4704,2021-09-30,2021-09-30,72.7608,18190.2000,18190.00
...,...,...,...,...,...,...,...,...,...,...,...,...
864,45933,60.0,4188.60,2021-10-29 03:51:25,1635479485,2,5453,2021-10-29,2021-10-29,70.5207,4231.2420,4188.60
865,45934,454.0,31693.74,2021-10-29 03:56:57,1635479817,2,5256,2021-10-29,2021-10-29,70.5207,32016.3978,31693.74
867,45938,260.0,18150.60,2021-10-29 06:28:24,1635488904,2,5402,2021-10-29,2021-10-29,70.5207,18335.3820,18150.60
871,45948,240.0,16754.40,2021-10-29 09:05:50,1635498350,2,5392,2021-10-29,2021-10-29,70.5207,16924.9680,16754.40
873,45954,210.0,14660.10,2021-10-29 09:51:40,1635501100,2,5354,2021-10-29,2021-10-29,70.5207,14809.3470,14660.10

In [37]:
total2 = total1[total1['rub']!=total1['Сумма оплаты']]
total2

,id,amount,rub,created_at,up,status,system_id,created_day,data,curs,sum,Сумма оплаты
61,44934,300.00,21828.00,2021-10-01 08:50:31,1633078231,2,5017,2021-10-01,2021-10-01,72.6642,21799.260000,14990.00
240,45130,500.00,36285.00,2021-10-06 14:59:12,1633532352,2,5330,2021-10-06,2021-10-06,72.5686,36284.300000,21385.00
283,45175,3769.00,273516.33,2021-10-08 07:27:47,1633678067,2,5353,2021-10-08,2021-10-08,72.2854,272443.672600,258616.33
410,45312,3404.29,245074.84,2021-10-12 04:33:59,1634013239,2,5389,2021-10-12,2021-10-12,71.6373,243874.144017,259974.84
412,45314,800.00,57592.00,2021-10-12 07:43:17,1634024597,2,5345,2021-10-12,2021-10-12,71.6373,57309.840000,27612.00
431,45335,1864.00,133536.96,2021-10-13 04:15:46,1634098546,2,5389,2021-10-13,2021-10-13,71.8801,133984.506400,118636.96
511,45430,341.50,24540.19,2021-10-15 08:24:01,1634286241,2,3387,2021-10-15,2021-10-15,71.7846,24514.440900,24540.19
737,45758,371.00,26289.06,2021-10-25 04:33:41,1635136421,2,5402,2021-10-25,2021-10-25,70.8623,26289.913300,26289.06
775,45809,225.00,15943.50,2021-10-25 09:33:19,1635154399,2,5354,2021-10-25,2021-10-25,70.8623,15944.017500,14900.00
799,45841,1000.00,0.00,2021-10-26 14:20:47,1635258047,2,5440,2021-10-26,2021-10-26,70.1345,70134.500000,499.00

In [25]:
total2['rub'].sum(), total2['Сумма оплаты'].sum()

(834605.88, 767443.38)

In [26]:
total2['rub'].sum() - total2['Сумма оплаты'].sum()

67162.5

In [36]:
payout_sept = payout[payout['created_at']<'2021-10-01']
display(payout_sept.merge(df, left_on='id', right_on='request' , how='left'))
payout_sept.merge(df, left_on='id', right_on='request' , how='left')['Сумма оплаты'].sum()
payout_sept.merge(df, left_on='id', right_on='request' , how='left')['sum'].sum()

,id,amount,rub,created_at,up,status,system_id,created_day,data,curs,sum,Сумма оплаты
0,44872,150.0,0.00,2021-09-29 11:41:52,1632915712,2,3320,2021-09-29,2021-09-29,72.5083,10876.2450,150.00
1,44873,500.0,0.00,2021-09-29 12:17:20,1632917840,2,4364,2021-09-29,2021-09-29,72.5083,36254.1500,500.00
2,44874,52.0,0.00,2021-09-29 13:40:59,1632922859,2,3849,2021-09-29,2021-09-29,72.5083,3770.4316,52.00
3,44875,162.0,0.00,2021-09-29 15:07:05,1632928025,2,2641,2021-09-29,2021-09-29,72.5083,11746.3446,162.00
4,44876,315.0,0.00,2021-09-29 20:23:05,1632946985,2,4268,2021-09-29,2021-09-29,72.5083,22840.1145,315.00
5,44877,317.0,0.00,2021-09-29 20:28:20,1632947300,2,4268,2021-09-29,2021-09-29,72.5083,22985.1311,317.00
6,44878,322.0,0.00,2021-09-29 20:28:25,1632947305,2,4268,2021-09-29,2021-09-29,72.5083,23347.6726,322.00
7,44879,267.0,0.00,2021-09-29 20:28:31,1632947311,2,4268,2021-09-29,2021-09-29,72.5083,19359.7161,267.00
8,44880,284.0,0.00,2021-09-29 20:28:38,1632947318,2,4268,2021-09-29,2021-09-29,72.5083,20592.3572,284.00
9,44881,300.0,0.00,2021-09-29 20:28:48,1632947328,2,4268,2021-09-29,2021-09-29,72.5083,21752.4900,300.00
10,44882,575.0,0.00,2021-09-29 20:49:10,1632948550,2,5093,2021-09-29,2021-09-29,72.5083,41692.2725,575.00
11,44883,44.0,3190.44,2021-09-29 20:49:25,1632948565,2,4699,2021-09-29,2021-09-29,72.5083,3190.3652,3190.44
12,44884,450.0,0.00,2021-09-29 21:34:08,1632951248,2,4991,2021-09-29,2021-09-29,72.5083,32628.7350,450.00
13,44885,150.0,10876.50,2021-09-30 01:16:20,1632964580,2,5159,2021-09-30,2021-09-30,72.7608,10914.1200,10876.50
14,44886,624.0,0.00,2021-09-30 07:16:23,1632986183,2,5176,2021-09-30,2021-09-30,72.7608,45402.7392,624.00
15,44887,59.0,0.00,2021-09-30 07:18:50,1632986330,2,697,2021-09-30,2021-09-30,72.7608,4292.8872,NaN
16,44888,500.0,0.00,2021-09-30 07:43:13,1632987793,2,5349,2021-09-30,2021-09-30,72.7608,36380.4000,500.00
17,44889,609.0,0.00,2021-09-30 08:01:27,1632988887,2,5069,2021-09-30,2021-09-30,72.7608,44311.3272,609.00
18,44890,40.0,2900.40,2021-09-30 08:30:00,1632990600,2,5364,2021-09-30,2021-09-30,72.7608,2910.4320,2900.40
19,44891,2517.0,0.00,2021-09-30 09:03:47,1632992627,2,146,2021-09-30,2021-09-30,72.7608,183138.9336,2517.00
20,44892,123.0,8918.73,2021-09-30 09:16:13,1632993373,2,4066,2021-09-30,2021-09-30,72.7608,8949.5784,8918.73
21,44893,135.0,0.00,2021-09-30 09:19:13,1632993553,2,2641,2021-09-30,2021-09-30,72.7608,9822.7080,135.00
22,44894,1260.0,0.00,2021-09-30 09:29:10,1632994150,2,5041,2021-09-30,2021-09-30,72.7608,91678.6080,1260.00
23,44895,1970.0,0.00,2021-09-30 09:49:35,1632995375,2,5040,2021-09-30,2021-09-30,72.7608,143338.7760,1970.00
24,44896,579.0,0.00,2021-09-30 10:07:21,1632996441,2,2720,2021-09-30,2021-09-30,72.7608,42128.5032,579.00
25,44897,4133.0,0.00,2021-09-30 10:12:44,1632996764,2,4545,2021-09-30,2021-09-30,72.7608,300720.3864,4133.00
26,44898,674.0,0.00,2021-09-30 10:35:00,1632998100,2,4812,2021-09-30,2021-09-30,72.7608,49040.7792,674.00
27,44899,581.0,0.00,2021-09-30 10:35:15,1632998115,2,5197,2021-09-30,2021-09-30,72.7608,42274.0248,581.00
28,44900,206.0,0.00,2021-09-30 12:26:08,1633004768,2,5333,2021-09-30,2021-09-30,72.7608,14988.7248,206.00
29,44901,2000.0,0.00,2021-09-30 13:12:57,1633007577,2,5287,2021-09-30,2021-09-30,72.7608,145521.6000,2000.00
30,44902,250.0,18190.00,2021-09-30 14:08:34,1633010914,2,4704,2021-09-30,2021-09-30,72.7608,18190.2000,18190.00
31,44903,250.0,18190.00,2021-09-30 14:08:41,1633010921,2,4749,2021-09-30,2021-09-30,72.7608,18190.2000,18190.00
32,44904,43.0,0.00,2021-09-30 16:01:26,1633017686,2,5328,2021-09-30,2021-09-30,72.7608,3128.7144,43.00
33,44905,60.0,0.00,2021-09-30 16:48:52,1633020532,2,5295,2021-09-30,2021-09-30,72.7608,4365.6480,60.00
34,44906,66.0,4802.16,2021-09-30 18:22:29,1633026149,2,4874,2021-09-30,2021-09-30,72.7608,4802.2128,4802.16
35,44907,45.0,3274.20,2021-09-30 20:52:02,1633035122,2,4699,2021-09-30,2021-09-30,72.7608,3274.2360,3274.20

1498801.7646000003

In [74]:
trans['balance'] = trans['balance'].apply(lambda x: float(str(x).replace(',', '.')))
trans

         user_id amount  balance           created_at         payment_type
0          14035  16,00   1158.0  2021-12-31 23:59:46  Транзакция по лидам
1           9111  14,00    209.0  2021-12-31 23:59:41  Транзакция по лидам
2           9111   0,00    195.0  2021-12-31 23:59:27  Транзакция по лидам
3          15501   0,00    388.0  2021-12-31 23:58:56  Транзакция по лидам
4          14217   0,00   2062.0  2021-12-31 23:58:44  Транзакция по лидам
...          ...    ...      ...                  ...                  ...
4897824    13483   0,00    420.0  2021-05-01 00:01:23  Транзакция по лидам
4897825    13483   0,00    420.0  2021-05-01 00:01:20  Транзакция по лидам
4897826     9069   0,00   2412.0  2021-05-01 00:01:02  Транзакция по лидам
4897827     2536   0,00    372.0  2021-05-01 00:00:56  Транзакция по лидам
4897828     7463   0,00   5136.0  2021-05-01 00:00:02  Транзакция по лидам

[4897829 rows x 5 columns]

In [75]:
trans1=trans.pivot_table(index = 'user_id',values = 'created_at', aggfunc = 'max').merge(trans, on=['user_id','created_at'] , how='left')#['balance'].sum()

In [76]:
trans1

      user_id           created_at  amount    balance            payment_type
0           9  2021-12-14 11:56:27  -17,00      46.50     Транзакция по лидам
1          10  2021-12-13 18:27:15    0,00     606.91     Транзакция по лидам
2          20  2021-12-23 12:22:27    0,00       0.00  Реферальное начисление
3          28  2021-12-31 23:57:35    0,00  499578.45     Транзакция по лидам
4          31  2021-12-29 13:29:25    0,00       0.00     Транзакция по лидам
...       ...                  ...     ...        ...                     ...
1315    17922  2021-12-18 11:35:01    0,00       0.00     Транзакция по лидам
1316    17925  2021-12-31 22:28:45    0,00      12.00     Транзакция по лидам
1317    17986  2021-12-30 16:25:35    0,00       0.00     Транзакция по лидам
1318    18034  2021-12-31 22:44:03    0,00     219.00     Транзакция по лидам
1319    18064  2021-12-31 23:44:19    0,00      34.00     Транзакция по лидам

[1320 rows x 5 columns]

In [77]:
trans1['user_id'].value_counts()

14256    14
3968     10
655       6
9308      6
4829      6
         ..
9140      1
9135      1
9111      1
9103      1
18064     1
Name: user_id, Length: 1231, dtype: int64

In [ ]:
trans1[trans1['user_id']==3968]

In [83]:
trans3 = trans1.pivot_table(index = 'user_id',values = 'balance', aggfunc = 'min')

In [84]:
trans3['balance'].sum()

8308595.02

In [62]:
trans2 =  trans.pivot_table(index = 'user_id',values = 'created_at', aggfunc = 'max').reset_index()
trans2#['user_id'].value_counts()

      user_id           created_at
0           9  2021-12-14 11:56:27
1          10  2021-12-13 18:27:15
2          20  2021-12-23 12:22:27
3          28  2021-12-31 23:57:35
4          31  2021-12-29 13:29:25
...       ...                  ...
1226    17922  2021-12-18 11:35:01
1227    17925  2021-12-31 22:28:45
1228    17986  2021-12-30 16:25:35
1229    18034  2021-12-31 22:44:03
1230    18064  2021-12-31 23:44:19

[1231 rows x 2 columns]

In [42]:
trans

         user_id amount  balance           created_at         payment_type
0          14035  16,00  1158,00  2021-12-31 23:59:46  Транзакция по лидам
1           9111  14,00   209,00  2021-12-31 23:59:41  Транзакция по лидам
2           9111   0,00   195,00  2021-12-31 23:59:27  Транзакция по лидам
3          15501   0,00   388,00  2021-12-31 23:58:56  Транзакция по лидам
4          14217   0,00  2062,00  2021-12-31 23:58:44  Транзакция по лидам
...          ...    ...      ...                  ...                  ...
4897824    13483   0,00   420,00  2021-05-01 00:01:23  Транзакция по лидам
4897825    13483   0,00   420,00  2021-05-01 00:01:20  Транзакция по лидам
4897826     9069   0,00  2412,00  2021-05-01 00:01:02  Транзакция по лидам
4897827     2536   0,00   372,00  2021-05-01 00:00:56  Транзакция по лидам
4897828     7463   0,00  5136,00  2021-05-01 00:00:02  Транзакция по лидам

[4897829 rows x 5 columns]